export enum NextAction {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  MOBILE_VERIFICATION = 'MOBILE_VERIFICATION',
  PROFILE_COMPLETION = 'PROFILE_COMPLETION',
  PHOTO_UPLOAD = 'PHOTO_UPLOAD',
  NONE = 'NONE',
}